### ISSUE TITLE
move `if (!realRead)` and similar checks outta `yebash` function

### ISSUE THREAD

**Issue by szborows** [szborows/yebash#4]
right now each `read` call by `/bin/bash` is overwhelmed by our checks. these checks should be moved to other place. (i'm still not sure where the right place is, since I've just started studying Urlich's TLC paper).

**Comment by Mrokkk** [comment]
Removed checking realRead in commit [aec1d37a6b10a0c1a82e78d3e0836b52d3857fe2](https://github.com/szborows/yebash/commit/aec1d37a6b10a0c1a82e78d3e0836b52d3857fe2)
